### ISSUE TITLE
Please update

### ISSUE THREAD

**Issue by FrankHB** [makotom/glibc-wsl#2]
Recently updated packages requires newer versions of `glibc` (notably, libstdc++ in `gcc-libs`). Many packages are broken with the current `glibc-2.33`.

I've worked around it by building manually patched `glibc` locally (after downgrading `gcc`, `gcc-libs`, `binutils`, `libtool` and `make` to some previous versions) and it seems just work, except that I found GCC LTO not working for my projects, so I downgraded it with `gcc-libs` again. Anyway, this is [an issue specific to GCC](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=100150), while some other packages still require newer versions of `glibc`, and likely everything in the userland would be broken without a proper update in future.

**Comment by FrankHB** [comment]
BTW, some tests fail in my build. I see this is because of the limitations in the WSL1 environment.
The only side effects I observe now are:

* `_dl_lookup_symbol_x` uses `rtld_mutex_dummy` (ld-linux-x86-64.so.2) instead of `rtld_lock_default_lock_recursive`/`rtld_lock_default_unlock_recursive` (ld-2.33.so).
* `__memcmp_avx2_movbe` uses 15 instructions instead of 13 in average in my programs on my testing machine (with Ryzen 9 4900HS), due to [this change](https://sourceware.org/pipermail/libc-alpha/2021-March/123867.html).

Not sure if they are specific to the configuration or the machine.

**Comment by makotom** [comment]
@FrankHB Thank you very much for your post! I'm actively working on an update, hopefully I can publish it soon.

**Comment by makotom** [comment]
https://github.com/makotom/glibc-wsl/releases/tag/2.35-2%4028-14f31b0 is now ready! At least for the time being it works for me. 🐱

**Comment by FrankHB** [comment]
The new release works for me. Thanks!

(I find the minor symbol mismatches are from my mistake of mixing the different test environments with [another patched glibc package](https://github.com/archlinuxcn/repo/blob/master/archlinuxcn/glibc-linux4/PKGBUILD). It is patched differently, but also outdated for now.)
